server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8090
          predicates:
            - Path=/auth/signup/attendee, /auth/signup/organization, /auth/auth
          filters:
            - StripPrefix=1
        - id: event_auth
          uri: https://eventmicroservice.herokuapp.com
          predicates:
            - Path=/event/save/organization
          filters:
            - StripPrefix=1
        - id: chat_auth
          uri: https://chatmicroservice.herokuapp.com
          predicates:
            - Path=/chat/save/attendee
          filters:
            - StripPrefix=1
        - id: event
          uri: https://eventmicroservice.herokuapp.com
          predicates:
            - Path=/event/**
          filters:
            - StripPrefix=1
            - GatewayTokenFilter
        - id: chat
          uri: https://chatmicroservice.herokuapp.com
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
            - GatewayTokenFilter
        - id: websocket
          uri: https://chatmicroservice.herokuapp.com
          predicates:
            - Path=/ws/**